import SwiftUI

/// Configures the EA (Executive Assistant) backend as an additional
/// sync destination. Lives alongside MySQLSettingsView; both can be
/// enabled simultaneously, or just one.
///
/// Auth is a single per-integration sync key generated by the EA server
/// (`php artisan ea:healthbeat-key:rotate` — printed once, stored
/// encrypted in `system_credentials.healthbeat_sync_key`). Not the
/// global EA API key.
struct EASettingsView: View {
    @State private var config: EAConfig = .load()
    @State private var revealKey = false
    @State private var savedConfirmation = false
    @State private var testResult: TestResult?
    @State private var isTesting = false
    @State private var confirmEAReset = false

    enum TestResult: Equatable {
        case success(serverTime: String, schemaVersion: Int, maxBatch: Int)
        case failure(String)
    }

    var body: some View {
        Form {
            Section("Endpoint") {
                Toggle("Enable EA destination", isOn: $config.enabled)

                LabeledContent("Base URL") {
                    TextField("https://ea.example.com", text: $config.baseURL)
                        .textInputAutocapitalization(.never)
                        .autocorrectionDisabled()
                        .keyboardType(.URL)
                        .multilineTextAlignment(.trailing)
                }

                HStack(alignment: .firstTextBaseline) {
                    Text("Sync Key")
                    Spacer()
                    if revealKey {
                        TextField("hbk_…", text: $config.syncKey)
                            .textInputAutocapitalization(.never)
                            .autocorrectionDisabled()
                            .font(.body.monospaced())
                            .multilineTextAlignment(.trailing)
                    } else {
                        SecureField("hbk_…", text: $config.syncKey)
                            .multilineTextAlignment(.trailing)
                    }
                    Button {
                        revealKey.toggle()
                    } label: {
                        Image(systemName: revealKey ? "eye.slash" : "eye")
                            .foregroundStyle(.secondary)
                    }
                    .buttonStyle(.plain)
                }
                Text("Copy the sync key from the EA web UI → /health-data → Settings.")
                    .font(.caption)
                    .foregroundStyle(.secondary)
            }

            Section("Connection Test") {
                Button {
                    Task { await runTest() }
                } label: {
                    HStack {
                        if isTesting { ProgressView().controlSize(.small).padding(.trailing, 4) }
                        Text("Test Connection")
                    }
                }
                .disabled(isTesting || !config.isConfigured && !(config.normalisedBaseURL != nil && !config.syncKey.isEmpty))

                if let result = testResult {
                    switch result {
                    case .success(let serverTime, let schemaVersion, let maxBatch):
                        Label("Connected — server time \(serverTime), schema v\(schemaVersion), batch ≤ \(maxBatch)", systemImage: "checkmark.circle.fill")
                            .foregroundStyle(.green)
                            .font(.callout)
                    case .failure(let msg):
                        Label(msg, systemImage: "xmark.octagon.fill")
                            .foregroundStyle(.red)
                            .font(.callout)
                    }
                }
            }

            Section {
                Button {
                    config.save()
                    savedConfirmation = true
                    Task {
                        try? await Task.sleep(nanoseconds: 1_200_000_000)
                        savedConfirmation = false
                    }
                } label: {
                    HStack {
                        Spacer()
                        Text(savedConfirmation ? "Saved ✓" : "Save")
                            .font(.body.weight(.semibold))
                        Spacer()
                    }
                }
                .disabled(savedConfirmation)
            } footer: {
                Text("Both backends can be enabled at the same time. EA mirrors what's written to MySQL — turn off MySQL only when you're sure EA has all the data you need.")
                    .font(.caption)
            }

            Section {
                Label("Run a full sync from the Sync tab", systemImage: "arrow.clockwise.icloud")
                    .font(.callout)
                Text("The first sync after enabling EA exports all Apple Health data (keep the screen on for the quick export), uploads it to EA in the background, and processes it server-side. Later syncs are incremental. Trigger it from the Sync tab.")
                    .font(.caption).foregroundStyle(.secondary)
            } header: {
                Text("Full sync")
            }

            Section {
                Button(role: .destructive) {
                    confirmEAReset = true
                } label: {
                    Label("Re-sync EA from scratch", systemImage: "arrow.triangle.2.circlepath")
                }
            } footer: {
                Text("Use this if EA's data was wiped on the server, or you want to rebuild it. It drops EA's baseline so the next Full Sync re-exports everything to EA (replacing its tables). MySQL is left untouched.")
                    .font(.caption)
            }
            .confirmationDialog(
                "Re-sync EA from scratch?",
                isPresented: $confirmEAReset, titleVisibility: .visible
            ) {
                Button("Drop EA baseline", role: .destructive) {
                    NotificationCenter.default.post(name: .healthBeatEAResetRequested, object: nil)
                }
                Button("Cancel", role: .cancel) {}
            } message: {
                Text("The next Full Sync will re-export all Apple Health data to EA, replacing its current tables. MySQL is unaffected.")
            }
        }
        .navigationTitle("Executive Assistant")
        .navigationBarTitleDisplayMode(.inline)
    }

    private func runTest() async {
        isTesting = true
        defer { isTesting = false }
        guard config.normalisedBaseURL != nil, !config.syncKey.isEmpty else {
            testResult = .failure("Enter a base URL and sync key first.")
            return
        }
        let service = EAService(config: config)
        do {
            let h = try await service.health()
            testResult = .success(serverTime: h.server_time, schemaVersion: h.schema_version, maxBatch: h.max_batch)
        } catch {
            testResult = .failure("\(error)")
        }
    }
}
